### ISSUE TITLE
[Gentoo] Build failed with commit a2404acae861135f74fecea885c0b3e3fe9193bd

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/dde-daemon#40]
I try to compile the latest version of dde-daemon with tag 3.2.3, but failed.
The errors I got were:
```
env GOPATH="/var/tmp/portage/dde-base/dde-daemon-3.2.3/work/dde-daemon-3.2.3/gopath:/var/tmp/portage/dde-base/dde-daemon-3.2.3/work/dde-daemon-3.2.3:/usr/share/gocode" go build -ldflags '-s -w' -o out/bin/dde-system-daemon  pkg.deepin.io/dde/daemon/bin/dde-system-daemon
# pkg.deepin.io/dde/daemon/system/gesture
core.c: In function ‘handle_gesture_events’:
core.c:214:10: error: ‘LIBINPUT_EVENT_GESTURE_TAP_BEGIN’ undeclared (first use in this function)
     case LIBINPUT_EVENT_GESTURE_TAP_BEGIN:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.c:214:10: note: each undeclared identifier is reported only once for each function it appears in
core.c:216:10: error: ‘LIBINPUT_EVENT_GESTURE_TAP_END’ undeclared (first use in this function)
     case LIBINPUT_EVENT_GESTURE_TAP_END:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.c: In function ‘handle_events’:
core.c:285:14: error: ‘LIBINPUT_EVENT_GESTURE_TAP_BEGIN’ undeclared (first use in this function)
         case LIBINPUT_EVENT_GESTURE_TAP_BEGIN:
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.c:286:14: error: ‘LIBINPUT_EVENT_GESTURE_TAP_UPDATE’ undeclared (first use in this function)
         case LIBINPUT_EVENT_GESTURE_TAP_UPDATE:
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.c:287:14: error: ‘LIBINPUT_EVENT_GESTURE_TAP_END’ undeclared (first use in this function)
         case LIBINPUT_EVENT_GESTURE_TAP_END:{
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:48: out/bin/dde-system-daemon] Error 2
make: *** Waiting for unfinished jobs....
```

It seems that some new added Types are undeclared. And these Types can't be found in libinput(https://wayland.freedesktop.org/libinput/doc/latest/group__base.html#ggac30276a06e8b1434b959f2c8dde74f7cae431f9d5995d1ad62154454000e7fae0). 

Need your help please.

**Comment by jouyouyun** [comment]
dde-daemon patch:  https://github.com/jouyouyun/tap-gesture-patches/blob/master/patches/dde-daemon_3.2.3.patch

**Comment by romildo** [comment]
This is still an issue for dde-daemon-3.9.0.

The patch mentioned above _does not apply_ cleanly anymore.

cc @jouyouyun

**Comment by felixonmars** [comment]
Thanks, updated in the Arch package.

**Comment by zhtengw** [comment]
@jouyouyun Thank you. Gentoo deepin-overlay updated.

**Comment by jouyouyun** [comment]
:smile:
